# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: products.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'products.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"6\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"~\n\x0fProductResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x0b\n\x03\x65\x61n\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\x12\x12\n\nbrut_price\x18\x04 \x01(\x05\x12\x11\n\tnet_price\x18\x05 \x01(\x05\x12\x17\n\x0f\x61\x64\x64itional_info\x18\x06 \x01(\t2c\n\x0fProductsService\x12P\n\x19\x43heckProductsAvailability\x12\x18.products.ProductRequest\x1a\x19.products.ProductResponseB\x0bZ\t/productsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t/products'
  _globals['_PRODUCTREQUEST']._serialized_start=28
  _globals['_PRODUCTREQUEST']._serialized_end=82
  _globals['_PRODUCTRESPONSE']._serialized_start=84
  _globals['_PRODUCTRESPONSE']._serialized_end=210
  _globals['_PRODUCTSSERVICE']._serialized_start=212
  _globals['_PRODUCTSSERVICE']._serialized_end=311
# @@protoc_insertion_point(module_scope)
